package com.app.chatserver.enums;

public enum ServerErrors {
    PHONE_EXIST_IN_DATABASE,
    USER_NAME_EXIST_IN_DATABASE,
    FILE_NOT_UPLOADED,
    PHONE_NUMBER_INCORRECT,
    USER_NAME_INCORRECT,
    USER_LAST_NAME_INCORRECT,
    USER_BIRTH_DATE_INCORRECT,
    NAME_INCORRECT,
    CODE_IS_NOT_EQUAL,
    CODE_IS_INVALID,
    TOKEN_INVALID,
    USER_NOT_REGISTERED_YET,
    INFORMATION_WAD_ADDED,
    USER_NOT_FOUND
}
